name: Test Pipeline

on:
  push:
    branches:
      - master
env:
  fileName: 'test.txt'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run test command
        run: echo "Hello from  Test Pipeline GitHub Actions"

      - name: Create file
        run: echo "This is a test file." > $fileName
